# Generated by Django 4.2.10 on 2024-02-27 08:49

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='api.participants', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_code',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_date',
            field=models.DateTimeField(default=api.models.return_date_time, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_day',
            field=models.DateField(null=True, verbose_name='Meeting Day'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='api.participants', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topic',
            field=models.CharField(max_length=180, null=True, verbose_name='Meeting Topic'),
        ),
    ]
