# Generated by Django 4.2.10 on 2024-02-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meeting_meeting_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='api.participants', verbose_name='Created By'),
        ),
    ]
