# Generated by Django 4.2.10 on 2024-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meeting_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='api.participants', verbose_name='Participants'),
        ),
    ]
